name: Deploy to offi.ceo VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ${{ secrets.VPS_PROJECT_PATH }}
            git reset --hard
            git pull origin main
            npm install
            npm run build
