name: Deploy to offi.ceo VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            set -e

            # Load your user profile so npm is in PATH
            if [ -f ~/.bash_profile ]; then
              source ~/.bash_profile
            elif [ -f ~/.bashrc ]; then
              source ~/.bashrc
            elif [ -f ~/.profile ]; then
              source ~/.profile
            fi

            cd ${{ secrets.VPS_PROJECT_PATH }}

            echo "➡️ Ensure GitHub in known_hosts"
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            echo "➡️ Fetch & reset to origin/main"
            git fetch --all
            git reset --hard origin/main

            echo "➡️ Install deps"
            npm install

            echo "➡️ Clean old build"
            rm -rf dist

            echo "➡️ Build fresh"
            npm run build

            echo "✅ Deploy complete!"
