name: Deploy to offi.ceo VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            set -e

            # Go to your project folder
            cd ${{ secrets.VPS_PROJECT_PATH }}

            echo "➡️ Fetching latest from origin"
            git fetch --all

            echo "➡️ Resetting to origin/main"
            git reset --hard origin/main

            echo "➡️ Installing dependencies"
            npm install

            echo "➡️ Cleaning old build"
            rm -rf dist

            echo "➡️ Building fresh"
            npm run build

            echo "✅ Deploy complete!"
