      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            set -e
            cd ${{ secrets.VPS_PROJECT_PATH }}
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            echo "➡️ Fetch & reset to origin/main"
            git fetch --all
            git reset --hard origin/main

-           echo "➡️ Install deps"
-           npm install
+           echo "➡️ Install deps"
+           bash -lc "npm install"

            echo "➡️ Clean old build"
            rm -rf dist

-           echo "➡️ Build fresh"
-           npm run build
+           echo "➡️ Build fresh"
+           bash -lc "npm run build"

            echo "✅ Deploy complete!"
